### ISSUE TITLE
Realign WSCD architecture

### ISSUE THREAD

**Issue by sander** [sander/hierarchical-deterministic-keys#27]
ARF 1.2.0 had the concept of separation between Wallet Driving Application (WDA), Wallet Creation Application (WCA), Wallet Secure Cryptographic Application (WSCA), Wallet Secure Cryptographic Device (WSCD). We took over these concepts in [context.md](https://github.com/sander/hierarchical-deterministic-keys/blob/5f1a31d0794cff73065a93a5696bebef6dd76633/context.md). In 1.3.0 and 1.4.0, WDA and WCA have been removed.

I also notice in discussing [feedback.md](https://github.com/sander/hierarchical-deterministic-keys/blob/5f1a31d0794cff73065a93a5696bebef6dd76633/feedback.md) that different people have different interpretations of where HDK should happen. I have interpreted it as happening within the WCA and outside of the WSCD. But in ARF 1.4.0, it seems that all key management needs to happen within the WSCD, which can be a hybrid, for example combining an HSM with a mobile phone running application code in its rich execution environment. This is also how in the “proof of association” work, a “distributed WSCD” is described.

I’m not convinced this makes Common Criteria certification of WSCDs easier. But let’s try.

This would be the generic HDK-based architecture with the “distributed WSCD” perspective:

![HDK-generic drawio](https://github.com/sander/hierarchical-deterministic-keys/assets/44112/3f240fd7-d1e0-4815-baa6-43fe09adf735)

This would be a hybrid example architecture with the “distributed WSCD” perspective:

![HDK-hybrid drawio](https://github.com/sander/hierarchical-deterministic-keys/assets/44112/ccf20f0f-515f-4f57-ae40-7669b7478ba3)

What do you think?

**Comment by sander-cb** [comment]
Iteration:

![HDK-hybrid-v2 drawio](https://github.com/sander/hierarchical-deterministic-keys/assets/93431675/c26cf76e-79ca-42a2-885c-6ed2c909e592)

- Move SCAL3 from WSCD to WI
- Consequentially, remove “Local native” WSCD component
- Have single interaction from WI to WSCD web server (was: application server)

**Comment by sander** [comment]
Iteration based on today’s feedback:

![HDK-hybrid-v2 drawio](https://github.com/sander/hierarchical-deterministic-keys/assets/44112/c3d58816-895c-4bda-af8d-0c18c2bcac3b)

- Move SCAL3 from WSCD to WI
- Consequentially, remove “Local native” WSCD component
- Have single interaction from WI to WSCD web server (was: application server)
- Explore option to delegate to wallet provider instead of relying party

**Comment by sander** [comment]
Discussed further today at Identity Week. We seem to agree that in this case, the WSCD+WSCA certification should have just the HSM+software as TOE, and set environmental objectives for the rest, such as provision of the WSCD interaction component. This should simplify the architecture, and make it a “Remote HSM” architecture instead of a “Hybrid” one.

**Comment by sander** [comment]
Simplified architecture visualisation:

![HDK-remote drawio](https://github.com/sander/hierarchical-deterministic-keys/assets/44112/0b704f02-a0b2-47f8-af30-78c02e46efc6)

**Comment by sander** [comment]
Discussed 2024-06-24: we'd like to include a diagram like this to illustrate what kind of architectures HDK enables.

**Comment by sander** [comment]
Discussed 2024-07-08: included the diagram in 43b442b131d51f080d0108e97b8db2badcbe45cb and reflected in `feedback.md`. So we can close this issue.
