### ISSUE TITLE
Provide roadmap and implementation advice

### ISSUE THREAD

**Issue by sander** [sander/hierarchical-deterministic-keys#53]
Feedback by @Sakurann at 2024-08-13 presentation at DE EUDIW Project: HDK now lists many options. Provide a roadmap and implementation advice to make it easier to get started.

**Comment by sander** [comment]
Discussed: let’s start with the table by @mickrau.

**Comment by mickrau** [comment]
**Issuance**
<img width="1567" alt="hdk_comp1" src="https://github.com/user-attachments/assets/4eb68249-9d80-4ad1-9f82-0b5d28bdffe3">

**Presentation**
<img width="441" alt="hdk_comp2" src="https://github.com/user-attachments/assets/811bcfe5-e313-4ccb-8a76-7dbf66414f55">

**Comment by sander** [comment]
Presented 2024-10-21, comments:

- some solutions hide the blinded keys from the wallet provider, while others don’t => consider the wallet provider as a specific type of issuer (ITE)
